import'bootstrap/dist/css/bootstrap.min.css';
//import $ from'jquery';
//import Popper from'popper.js';
import'bootstrap/dist/js/bootstrap.bundle.min';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import * as serviceWorker from './serviceWorker';
import CollectionOfGenreLists from './components/MusicLists';
import Header from './components/Header';
import Home from './components/Home';
import ProductTable from './components/ProductTable';
//import { Col } from 'reactstrap';

const TESTLINKS = [
    {genre: 'Classic Rock', author: 'Led Zeppelin', title: 'Stairway to Heaven', link: 'https://www.youtube.com/watch?v=X791IzOwt3Q'},
    {genre: 'Classic Rock', author: 'Led Zeppelin', title: 'Kashmir', link: 'https://www.youtube.com/watch?v=tzVJPgCn-Z8'},
    {genre: 'Alternative', author: 'Siames', title: 'Mr Fear', link: 'https://www.youtube.com/watch?v=EKLWC93nvAU'},
    {genre: 'Alternative', author: 'Siames', title: 'Summer Nights', link: 'https://www.youtube.com/watch?v=hM7Eh0gGNKA'},
    {genre: 'Alternative', author: 'Siames', title: 'The Wolf', link: 'https://www.youtube.com/watch?v=lX44CAz-JhU'}
];


const PRODUCTS = [
    {catagory: 'Sporting Goods', price: '$49.99', stocked: true, name: 'Football'},
    {catagory: 'Sporting Goods', price: '$9.99', stocked: true, name: 'Baseball'},
    {catagory: 'Sporting Goods', price: '$29.99', stocked: false, name: 'Basketball'},
    {catagory: 'Electronics', price: '$99.99', stocked: true, name: 'iPod Touch'},
    {catagory: 'Electronics', price: '$349.99', stocked: false, name: 'iPhone 5'},
    {catagory: 'Electronics', price: '$149.99', stocked: true, name: 'Nexus 7'}
];


class App extends React.Component{
    render(){
        return (           
            <div className="container">

                <div className="row">
                    <div className="col-xs-10 col-xs-offset-1">
                        <Header/>
                    </div>
                </div>

                <p>Text generated by app component</p>

                <div className="row">
                    <div className="col-xs-10 col-xs-offset-1">
                        <Home/>
                    </div>
                </div>

                <div>
                    <CollectionOfGenreLists testlinks={TESTLINKS}/>
                </div>

                <div>
                    <ProductTable products={PRODUCTS}/>
                </div>
            </div>
        );
    }
}

ReactDOM.render(
    <App />,
    document.getElementById('root'));

serviceWorker.unregister();


